exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
lsi: false
name: pld
markdown: kramdown
paginate: 5
highlighter: true
safe: true

css:
  - /css/syntax.css
  - /css/reset.css
  - /css/fonts.css
  - /css/text.css
  - /css/grid.css
  - /css/custom.css
